# site name
# 站点名
prefixName: なごりゆき
siteName: 走私心动
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: tou.jpg
url: /
description: 半身风雨半身伤，半句别恨半心凉。
cdn: https://cdn.jsdelivr.net/gh/lixinlidaye/cdn@cd7e304209dc7c2c1aee50441313439f705fe7e9/
pjax: 1
# 1开启
mathjax: 0

notice: 二斤桃花酿做酒，万杯不及你温柔
# lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    # 生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    # 资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    # 随想: {path: /categories/随想/, fa: fa-commenting-o },
    # 转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    # 图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura }
    # Lab: {path: /lab/, fa: fa-cogs },
  } }
  客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/lixinlidaye/cdn@master/0.jpg
  - https://cdn.jsdelivr.net/gh/lixinlidaye/cdn@master/1.jpg
  - https://cdn.jsdelivr.net/gh/lixinlidaye/cdn@master/2.jpg
  - https://cdn.jsdelivr.net/gh/lixinlidaye/cdn@master/3.jpg
  - https://cdn.jsdelivr.net/gh/lixinlidaye/cdn@master/4.jpg
  - https://cdn.jsdelivr.net/gh/lixinlidaye/cdn@master/5.jpg
  - https://cdn.jsdelivr.net/gh/lixinlidaye/cdn@master/6.jpg
  - https://cdn.jsdelivr.net/gh/lixinlidaye/cdn@master/7.jpg
  - https://cdn.jsdelivr.net/gh/lixinlidaye/cdn@master/tx.jpg
# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: https://github.com/honjun/hexo-theme-sakura/blob/master/README-zh_cn.md, title: Sakura, desc: 本站 hexo 主题, img: sakura.jfif}
  - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: 给他打波广告, img: bl.png}
  - {url: /, title: 万事屋, desc: 空着好看, img: yinshi.jpg}



# your site build time or founded date
# 你的站点建立日期
siteBuildingTime: 01/01/2020

#(社交按钮)social  url, img PC端配置
social:
  github: {url: https://github.com/lixinlidaye, img: github.png}
  # qq: {url: http://wpa.qq.com/msgrd?v=3&uin=2138427737&site=qq&menu=yes, img: /blog/fengxiang/qq.png}
  wechat: {url: /#, qrcode: wx.jpg, img: wechat.png }
  # wangzhan: {url: http://www.toprootman.cn, img: /blog/fengxiang/wdwz.png}
  bilibili: {url: https://space.bilibili.com/56196833, img: bilibili.png}
  # qzone: {url: https://user.qzone.qq.com/2138427737, img: /blog/fengxiang/qzone.png}

#social  url, img 移动端配置
msocial:
  github: {url: https://github.com/lixinlidaye, fa: fa-github, color: 333}
  qq: {url: http://wpa.qq.com/msgrd?v=3&uin=2322368970&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal: /#
  alipay: zfbsq.jpg	
  wechat: wxsq.jpg
  wechatSQ: wxsq.jpg


# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ

